[package]
name = "kosmos"
version = "0.2.0"
edition = "2024"

[workspace]
members = [
    "kosmos-bin",
    "kosmos-std"
]

[dependencies]
bootloader = { version = "0.9", features = ["map_physical_memory"] }
volatile = "0.2.6"
lazy_static = { version = "1.0", features = ["spin_no_std"] }
spin = "0.5.2"
x86_64 = "0.14.2"
uart_16550 = "0.6.0"
pic8259 = "0.10.1"
pc-keyboard = "0.7.0"
linked_list_allocator = "0.9.0"
crossbeam-queue = { version = "0.3.11", default-features = false, features = ["alloc"] }
conquer-once = { version = "0.2.0", default-features = false }
futures-util = { version = "0.3.4", default-features = false, features = ["alloc"] }
fatfs = { git = "https://github.com/rafalh/rust-fatfs", default-features = false, features = ["alloc", "lfn"] }
xmas-elf = "0.10.0"

[[bin]]
name = "kosmos"
test = true
bench = false

[[test]]
name = "should_panic"
harness = false

[[test]]
name = "stack_overflow"
harness = false

[lib]
doctest = false

[package.metadata.bootimage]
run-args = [
    "-serial", "stdio",
    "-drive", "format=raw,file=qemu-fat32.img,if=ide,bus=1,unit=0"
]
test-args = [
    "-device", "isa-debug-exit,iobase=0xf4,iosize=0x04", "-serial", "stdio",
    "-display", "none",
    "-drive", "format=raw,file=qemu-fat32.img,if=ide,bus=1,unit=0"
]
test-success-exit-code = 33
test-timeout = 150

# 'cargo build'
[profile.dev]
debug = 0
strip = "symbols"

# 'cargo build --release'
[profile.release]
